Repository Talend/tcommon-studio-se, pull requests merged in 2019-12, with the labels that each got.

#2884 Rlecomte/fix/tdi 42188 harden deserialization 2
  main/plugins/org.talend.librariesmanager/pom.xml
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/GetJarsToRegister.java
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/NoHeaderObjectInputStream.java
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/RunTrace.java
Labels: Reviewing

#2921 fix tos log4j default
  main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/Log4jUtil.java
Labels: Build running

#2909 bugfix(TUP-22500):jars already existed on nexus still try to upload
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java
Labels: buildme

#2947 bugfix(TUP-25194)External jar sync issue in studio using tLibraryLoad…
  main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
Labels: buildme

#2967 fix(TUP-25075)Studio download jars but donot dynamically distribute some
  main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareMavenArtifactsOnStartup.java
Labels: Build running

#2968 fix(TUP-25604):Import Duplicate metedata under Tacokit
  main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ResourcesManager.java
Labels: Build running

#2970 fix(TUP-6493)File path can't change when inputting a file path for the
  main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/dialog/OpenXSDFileDialog.java
Labels: Build running

#2971 fix(TUP-24475):studio metadata ui is wrong for exasol database, is different ui with component part
  main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
Labels: Build running
