Repository Talend/tcommon-studio-se, pull requests merged in 2019-08, with the labels that each got.

#2633 feat(TDI-40339): add Snowflake SQL Templates
  main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Snowflake/SnowflakeCreateSourceTable.sqltemplate
  main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Snowflake/SnowflakeCreateTargetTable.sqltemplate
  main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Snowflake/SnowflakeDropSourceTable.sqltemplate
  main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Snowflake/SnowflakeDropTargetTable.sqltemplate
  main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Snowflake/SnowflakeMerge.sqltemplate
Labels: Need review

#2666 fix(TDI-42034): update Redshift jar to 1.2.32.1056
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
Labels: Need review

#2675 fix(TUP-24232)JDBC metadata connection for Redshift when exported as context, unable to retrieve schema
  main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
Labels: Build running

#2683 fix(TUP-24248)when edit the metadata, the display content is different as when created
  main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/json/JsonTreePopulator.java
Labels: Build running

#2689 fix(TUP-23568):nexus password display in studio error log (#2564)
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/ResolverExceptionHandler.java
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/TalendMavenResolver.java
  main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
  main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/nexus/NexusDownloadHelperWithProgress.java
  main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
  test/plugins/org.talend.core.runtime.test/src/org/talend/core/nexus/ResolverExceptionHandlerTest.java
  test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelperTest.java
  test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/PomUtilTest.java
Labels: Build running

#2692 fix : TDI-42776
  main/plugins/org.talend.librariesmanager/resources/java/routines/Numeric.java
Labels: Need review, bug
