Repository Talend/tcommon-studio-se, pull requests merged in 2019-03, with the labels that each got.

#2280 Dsylaiev/tdi 41808 fix showing pass nzload (#2276)
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
Labels: Backport, Need review

#2285 Dsylaiev/tdi 41808 fix showing pass nzload (#2276)
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
Labels: Backport, Need review

#2284 Dsylaiev/tdi 41808 fix showing pass nzload (#2276)
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
Labels: Backport

#2283 Dsylaiev/tdi 41808 fix showing pass nzload (#2276)
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
Labels: Backport

#2282 Dsylaiev/tdi 41808 fix showing pass nzload (#2276)
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
Labels: Backport

#2281 Dsylaiev/tdi 41808 fix showing pass nzload (#2276)
  main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
Labels: Backport

#2297 fix(TDI-41951): special chars in column comment (#2293)
  main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
Labels: Backport

#2298 fix(TDI-41951): special chars in column comment (#2293)
  main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
Labels: Backport

#2299 fix(TDI-41951): special chars in column comment (#2293)
  main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
Labels: Backport

#2300 fix(TDI-41951): special chars in column comment (#2293)
  main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
Labels: Backport

#2264 fix(TDI-41790): change mapping for numbers
  main/plugins/org.talend.core.runtime/mappings/mapping_Vertica.xml
Labels: Need review

#2305 fix(TUP-22357)Cannot edit properties for joblet
  main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/image/ImageUtils.java
Labels: Build running

#2313 fix(TUP-22420)Exchange should not be in toolbar if -Dtalend.disable.internet=true
  main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ActionBarBuildHelper.java
Labels: Build running

#2317 fix(TDI-41876):Importing job from 6.2.1 to 7.1.1 is throwing error. (…
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolAvroHelper.java
Labels: Backport
