Repository Talend/tcommon-studio-se, pull requests merged in 2020-05, with the labels that each got.

#3245 fix(TDI-44093): Add method that checks if string wrapped by quotes
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TalendQuoteUtils.java
  main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
Labels: Build running, Need review

#3244 Jzhang/feat/tup 26284 upgrade aws sdk for driver in metadata
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
Labels: Build running

#3264 fix(TUP-26990):Possible conflict in talend project
  main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java
Labels: Build running

#3271 fix(TUP-26990):Possible conflict in talend project (#3264)
  main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java
Labels: Build running

#3246 bugfix(TUP-26956):Update Studio top bar to reflect monthly deliveries
  main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
  main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchWindowAdvisor.java
Labels: Build running

#3253 fix(TUP-26961):When save/delete a test case, it might break the poms/CI
  main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/documentation/ERepositoryActionName.java
  main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
Labels: Build running

#3226 bugfix(TUP-24445):Testcase will list under the wrong job after do imp…
  main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
  main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
  main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java
Labels: Build running

#3266 fix(TUP-27053): fix job starting script error and job startup without…
  main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
  test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPomTest.java
Labels: Build running

#3267 fix(TUP-27000):Talend Salesforce Einstein connector Repository connection issue in Talend 7.3
  main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/dnd/SalesforceComponentDndFilter.java
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
Labels: Build running

#3265 TUP-27046 Replace the "Added context" wizard message.
  main/plugins/org.talend.metadata.managment.ui/src/main/java/messages.properties
  main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/ShowAddedContextdialog.java
Labels: Build running

#3285 bugfix(TUP-27186)Create JDBC-sybase-anywhere connection need upload driver two times
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
Labels: Build running

#3293 fix(TUP-27077): NoClassDefFoundException when using "independent process to run subjob" and tAzureAdlsGen2Input
  main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
Labels: Build running

#3294 fix(TUP-27077): NoClassDefFoundException when using "independent proc…
  main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
Labels: Build running

#3282 Hwang/tup 26994
  main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/DefaultTokenCollector.java
  main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/contentProvider/DynamicContentProvider.java
  main/plugins/org.talend.registration/src/main/java/org/talend/registration/register/RegisterManagement.java
Labels: Build running

#3289 fix(TDI-44128): delete axis2 jars
  main/plugins/org.talend.libraries.apache.axis2/lib/axis2-kernel-1.5.jar
  main/plugins/org.talend.libraries.apache.axis2/lib/axis2-transport-http-1.5.jar
  main/plugins/org.talend.libraries.apache.axis2/lib/axis2-transport-local-1.5.jar
Labels: Need review

#3344 fix(TDI-44169): remove xmlrpc_3.0 from studio
  main/plugins/org.talend.libraries.apache.xml/lib/.gitignore
  main/plugins/org.talend.libraries.apache.xml/pom.xml
Labels: Need review
