Repository Talend/tcommon-studio-se, pull requests merged in 2020-08, with the labels that each got.

#3539 Enable precision check for Timestamp datatype
  main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
Labels: Backport, Need review

#3495 Enable precision check for Timestamp datatype.
  main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
Labels: Need review

#3460 TUP-27849
  main/features/org.talend.libraries.jdbc.feature/feature.xml
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
  main/plugins/org.talend.libraries.jdbc.postgresql/.classpath
  main/plugins/org.talend.libraries.jdbc.postgresql/.project
  main/plugins/org.talend.libraries.jdbc.postgresql/META-INF/MANIFEST.MF
  main/plugins/org.talend.libraries.jdbc.postgresql/META-INF/eclipse.inf
  main/plugins/org.talend.libraries.jdbc.postgresql/build.properties
  main/plugins/org.talend.libraries.jdbc.postgresql/lib/postgresql-8.4-703.jdbc4.jar
  main/plugins/org.talend.libraries.jdbc.postgresql/lib/postgresql-9.4-1201.jdbc41.jar
  main/plugins/org.talend.libraries.jdbc.postgresql/licenses/postgresql_license.txt
  main/plugins/org.talend.libraries.jdbc.postgresql/pom.xml
  main/plugins/org.talend.metadata.managment/plugin.xml
  pom.xml
Labels: Build running

#3551 fix(TUP-27820):context group with same key causing the issue.
  main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/nattableTree/ContextAutoResizeTextPainter.java
  main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/nattableTree/ContextNatTableBackGroudPainter.java
Labels: Build running

#3577 fix(TUP-28078)metadata folder generated under .../poms/jobs when create new connection in remote project
  main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
Labels: Build running

#3533 fix(TUP-28134):TCK Components shown as hidden by default in the palette
  main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/component/settings/ComponentsSettingsHelper.java
Labels: Build running

#3582 feat(TUP-28403)Update icons for 741 studio
  main/plugins/org.talend.common.ui.runtime/icons/component_missing.gif
  main/plugins/org.talend.common.ui.runtime/icons/component_missing.png
  main/plugins/org.talend.common.ui.runtime/icons1/project_wiz.png
  main/plugins/org.talend.common.ui.runtime/icons1/talend-picto-small.gif
  main/plugins/org.talend.common.ui.runtime/icons1/talend-picto.gif
  main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/image/ECoreImage.java
  main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/image/EImage.java
  main/plugins/org.talend.core.ui/icons/project_wiz.png
  main/plugins/org.talend.core.ui/icons/talend-picto-small.gif
  main/plugins/org.talend.core.ui/icons/talend-picto.gif
  main/plugins/org.talend.core/icons/project_wiz.png
  main/plugins/org.talend.core/icons/talend-picto-small.gif
  main/plugins/org.talend.core/icons/talend-picto.gif
  main/plugins/org.talend.helpers/icons/appli_16x16.png
  main/plugins/org.talend.rcp/icons/appli_16x16.gif
  main/plugins/org.talend.rcp/icons/appli_16x16.png
  main/plugins/org.talend.rcp/icons/appli_24x24.png
  main/plugins/org.talend.rcp/icons/appli_32x32.gif
  main/plugins/org.talend.rcp/icons/appli_32x32.png
  main/plugins/org.talend.rcp/icons/appli_48x48.gif
  main/plugins/org.talend.rcp/icons/appli_48x48.icns
  main/plugins/org.talend.rcp/icons/appli_48x48.png
  main/plugins/org.talend.rcp/icons/designer.ico
Labels: Build running
