Repository Talend/tcommon-studio-se, pull requests merged in 2020-02, with the labels that each got.

#3009 feat(TUP-25834)Upgrade postgres to support v12
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
Labels: Build running

#3051 bugfix(TUP-26031):Cannot connect successfully for mongDB which is
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/INOSQLService.java
Labels: Build running

#3056 bugfix(TUP-26064) Change to https for maven central
  main/plugins/org.talend.designer.maven/resources/templates/maven_user_settings.xml
Labels: Build running

#3017 fix(TDI-42965):Mysql/MariaDB mapping issue for dynamic schema
  main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
Labels: Need review

#3066 fix(TUP-26032):fix sparkstreaming job convert problem.
  main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java
  test/plugins/org.talend.core.repository.test/src/org/talend/repository/utils/ConvertJobsUtilTest.java
Labels: Build running

#3021 fix(TBD-9884) : Missing log42 conf on Yarn side
  .gitignore
  main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java
  main/plugins/org.talend.core/.classpath
  main/plugins/org.talend.core/.project
  main/plugins/org.talend.core/META-INF/MANIFEST.MF
  main/plugins/org.talend.core/build.properties
  main/plugins/org.talend.core/pom.xml
  main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
  test/plugins/org.talend.core.test/.classpath
  test/plugins/org.talend.core.test/.project
  test/plugins/org.talend.core.test/src/org/talend/designer/runprocess/ProcessorUtilitiesTest.java
Labels: needs review

#3074 bugfix(TUP-26123) Update copyright date
  i18n/plugins/org.talend.rcp.nl/plugin_de.properties
  i18n/plugins/org.talend.rcp.nl/plugin_en.properties
Labels: Build running

#3078 bugfix(TUP-26136): Fix java version parsing
  main/plugins/org.talend.utils/src/main/java/org/talend/utils/JavaVersion.java
  test/plugins/org.talend.utils.test/src/org/talend/utils/JavaVersionTest.java
Labels: Build running

#3081 fix(TDI-42965): Change back Mysql Mapping default talend type for BINARY/BIT
  main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
Labels: Need review
